version: '3'

services:
  pg-server:
    image: postgres
    container_name: pg-server
    ports:
      - '5432:5432'
    networks:
      - cve-manager-ntw
    volumes:
      - cve-manager:/cve-manager
      - "./database:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cve:
    build:
      context: .
      dockerfile: Dockerfile     
    container_name: cve-manager
    image: cve-manager:latest
    networks:
      - cve-manager-ntw    
    depends_on:
      - pg-server
    working_dir: /cve-manager
    restart: always
    stdin_open: true 
    tty: true         
    volumes:
      - cve-manager:/cve-manager  

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - cve-manager-ntw    
    depends_on:
      - pg-server    
    restart: always
    ports:
      - '8080:8080'
    environment:     
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_SERVER_PORT=5432

volumes:
  cve-manager:
    driver: local
    driver_opts:
      type: none
      device: ./cve-manager
      o: bind
networks:
  cve-manager-ntw:
    driver: bridge